### ISSUE TITLE
[Bug Report] rrreol-core run error on Windows and macOS platform

### ISSUE THREAD

**Issue by Himself65** [AimonaStudio/rrreol#152]
for more detail see the azure pipeline recently

**Comment by Himself65** [comment]
@langyo @abc1763613206 

Could someone help me to fix platform trouble?

**Comment by Himself65** [comment]
CI url: https://761282619.visualstudio.com/rrreol/_build/results?buildId=42

**Comment by Himself65** [comment]
now, It's only crash on Windows. I have no idea why a crash

and I'm using a util function to handle each platform which transfers end-line to `\n`, but still

https://github.com/AimonaStudio/rrreol/blob/6d97ac1a0bca9f01a532eb162c83b105e18402f8/packages/rrreol-core/src/utils/helpers.js#L21-L39

**Comment by langyo** [comment]
I don't know what happens, but I realized this line:
https://761282619.visualstudio.com/rrreol/_build/results?buildId=42&view=logs&jobId=27b6f328-3fef-5c06-072a-7ce961087861&taskId=41ec2f46-49c8-59f7-0157-275ec8e451b3&lineStart=102&lineEnd=103&colStart=1&colEnd=1
（Line 110）

Why it showed the undefined?

**Comment by Himself65** [comment]
i don’t know
it’s okay on my windows pc

―― by Himself65 Outlook<https://aka.ms/qtex0l>
________________________________
发件人: 伊欧 <notifications@github.com>
发送时间: Sunday, May 26, 2019 5:12:00 PM
收件人: AimonaStudio/rrreol
抄送: 扩散性百万甜面包; Assign
主题: Re: [AimonaStudio/rrreol] [Bug Report] rrreol-core run error on Windows and macOS platform (#152)


I don't know what happens, but I realized this line:
https://761282619.visualstudio.com/rrreol/_build/results?buildId=42&view=logs&jobId=27b6f328-3fef-5c06-072a-7ce961087861&taskId=41ec2f46-49c8-59f7-0157-275ec8e451b3&lineStart=102&lineEnd=103&colStart=1&colEnd=1
（Line 110）

Why it showed the undefined?

―

**Comment by Himself65** [comment]
After thinking twice, we will not support windows CI
