### ISSUE TITLE
Windowns10平台上不能使用rrreol

### ISSUE THREAD

**Issue by developers-youcong** [AimonaStudio/rrreol#165]
错误描述:
安装rrreol-core报错
![image](https://user-images.githubusercontent.com/45055576/59501908-1ef11000-8ecf-11e9-9064-c09d658cad1c.png)
使用npm i @rrreol-core则安装成功。但是这时又会出现一个问题，即便已经全局安装了@rrreol-core模块但是仍然会报错，这时的错误信息为:
![image](https://user-images.githubusercontent.com/45055576/59502018-5fe92480-8ecf-11e9-9cee-6083c039ab59.png)
明明已经安装好了模块，为什么会出现这种情况，正常找不到模块是因为项目中引入了该模块但没有这个模块才导致这样的错误。

**Comment by Himself65** [comment]
包名是@rrreol/xxx

**Comment by developers-youcong** [comment]
这是参考文档上写的代码,如图:
![image](https://user-images.githubusercontent.com/45055576/59545535-20175100-8f52-11e9-8544-b90f9201647a.png)

描述:按照你文档上一模一样的写，模块提示缺失后也通过命令安装为什么还会报模块找不到了，如图:
![image](https://user-images.githubusercontent.com/45055576/59545541-58b72a80-8f52-11e9-8a26-22303a15eb72.png)

如果你是说给js文件里面的导入模块加上@rreol-core，那样也还是一样报模块找不到。

另外我的node.js版本是8.15.0(不知道是否跟版本有关系还是)。

**Comment by Himself65** [comment]
1. 文档的确很久没更新了
2. 项目名称叫@rrreol/xxx
