### ISSUE TITLE
在js里引入报错：require('@rrreol/core')

### ISSUE THREAD

**Issue by zhouhangzooo** [AimonaStudio/rrreol#166]
我下载命令为：npm i @rrreol/core@0.1.1 -g（使用npm i @rrreol/core -g结果也报错）
![1560839382(1)](https://user-images.githubusercontent.com/37395573/59658325-db9be780-91d5-11e9-9061-289a4a3bddbe.jpg)

使用以下代码报错：
const rrreol = require('@rrreol/core')
const judge = new rrreol.Judge('./1.cpp')
judge.load(__dirname, {
  input: /[0-9]+.in$/,
  output: /[0-9]+.out$/
})
judge.exec() // 开始测试

报错：
在js中使用 const rrreol = require('@rrreol/core');报错，错误为
Error: Cannot find module '@rrreol/core'

想请问一下原因和有没有相关的实例，另外如有文档说明请发一下链接地址。谢谢！

**Comment by Himself65** [comment]
与此项目无关问题，仅仅是你不会用nodejs而已
