### ISSUE TITLE
下载了项目然后使用yarn test报错

### ISSUE THREAD

**Issue by zhouhangzooo** [AimonaStudio/rrreol#167]
D:\test\rrreol-master>yarn test
yarn run v1.13.0
$ lerna run test
lerna notice cli v3.14.1
lerna info Executing command in 2 packages: "yarn run test"
lerna info run Ran npm script 'test' in '@rrreol/ui' in 11.1s:
$ jest
lerna ERR! yarn run test exited 1 in '@rrreol/core'
lerna ERR! yarn run test stdout:
$ cross-env NODE_ENV=test jest -i
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:
FAIL test/unit/judge.test.js (9.003s)
  ● Judge check test › should emit check running success

    TypeError: judge.rawListeners is not a function

      72 |     const fm1 = FileManager.of().loadContent('1\n2\n')
      73 |     const fm2 = FileManager.of().loadContent('1\n2\n')
    > 74 |     judge.rawListeners('check')
         |           ^
      75 |       .map(f => f(fm1, fm2))
      76 |       .every(v => expect(v).toBeTruthy())
      77 |   })

      at Object.rawListeners (test/unit/judge.test.js:74:11)

PASS test/unit/fileManager.test.js
PASS test/unit/helpers.test.js
FAIL test/unit/runner.test.js
  ● Runner execUnsafe test › should execUnsafe run success with no input

    TypeError: file.isFile is not a function

      10 |     readdirSync(path, { withFileTypes: true })
      11 |       .forEach(file =>
    > 12 |         file.isFile() &&
         |              ^
      13 |         name.test(file.name) &&
      14 |         removeSync(join(path, file.name))
      15 |       )

      at isFile (src/utils/fs.js:12:14)
          at Array.forEach (<anonymous>)
      at forEach (src/utils/fs.js:11:8)
      at Object.<anonymous> (test/unit/runner.test.js:49:5)

  ● Runner execUnsafe test › should execUnsafe run success with input

    TypeError: file.isFile is not a function

      10 |     readdirSync(path, { withFileTypes: true })
      11 |       .forEach(file =>
    > 12 |         file.isFile() &&
         |              ^
      13 |         name.test(file.name) &&
      14 |         removeSync(join(path, file.name))
      15 |       )

      at isFile (src/utils/fs.js:12:14)
          at Array.forEach (<anonymous>)
      at forEach (src/utils/fs.js:11:8)
      at Object.<anonymous> (test/unit/runner.test.js:49:5)

FAIL test/unit/fs.test.js
  ● Test-Utils removeFiles test › should match file

    TypeError: file.isFile is not a function

      16 |     readdirSync(__dirname, { withFileTypes: true })
      17 |       .forEach(file =>
    > 18 |         file.isFile() &&
         |              ^
      19 |         /^test$/.test(file.name) &&
      20 |         expect(file.name).toEqual('test')
      21 |       )

      at isFile (test/unit/fs.test.js:18:14)
          at Array.forEach (<anonymous>)
      at Object.forEach (test/unit/fs.test.js:17:8)

  ● Test-Utils removeFiles test › should remove file through regex

    TypeError: file.isFile is not a function

      10 |     readdirSync(path, { withFileTypes: true })
      11 |       .forEach(file =>
    > 12 |         file.isFile() &&
         |              ^
      13 |         name.test(file.name) &&
      14 |         removeSync(join(path, file.name))
      15 |       )

      at isFile (src/utils/fs.js:12:14)
          at Array.forEach (<anonymous>)
      at forEach (src/utils/fs.js:11:8)
      at Object.<anonymous> (test/unit/fs.test.js:44:5)

PASS test/unit/compiler.test.js
PASS test/environment/compile.test.js
PASS test/unit/logger.test.js
PASS test/unit/index.test.js

Test Suites: 3 failed, 6 passed, 9 total
Tests:       5 failed, 37 passed, 42 total
Snapshots:   0 total
Time:        18.183s
Ran all test suites.
error Command failed with exit code 1.

lerna ERR! yarn run test exited 1 in '@rrreol/core'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Himself65** [comment]
请说出您nodejs的版本，还有是否先前运行过`yarn install`

**Comment by zhouhangzooo** [comment]
我之前使用的nodejs是8.5版本，换成10.0就好了，请问接下来使用什么命令运行项目呢？cd ./packages/rrreol-xxx
进入这个文件夹了，然后呢？

**Comment by Himself65** [comment]
君Nodejs本当上手

**Comment by zhouhangzooo** [comment]
您好，我的需求是我想通过node.js的方式对本地一个.cpp文件进行测评，应该是使用RRReol-Core，请问应使用什么方法呢？

**Comment by Himself65** [comment]
您可以参考一下 `/test` 文件夹下的测试，目前项目暂未写完，没有更新文档的必要

**Comment by zhouhangzooo** [comment]
这样，也就是说RRReol-Core等功能现在还不能使用吗？

**Comment by Himself65** [comment]
可以，测评部分可以，您可以参考一下 `/test` 文件夹下的测试

**Comment by zhouhangzooo** [comment]
好的，谢谢！
